definitions:
  domain.AccountType:
    enum:
    - bank
    - cash
    - credit_card
    - investment
    - other
    type: string
    x-enum-varnames:
    - AccountTypeBank
    - AccountTypeCash
    - AccountTypeCreditCard
    - AccountTypeInvestment
    - AccountTypeOther
  dto.AccountResponse:
    properties:
      color:
        type: string
      created_at:
        type: string
      currency:
        type: string
      icon:
        type: string
      id:
        type: string
      initial_balance:
        type: number
      name:
        type: string
      tenant_id:
        type: string
      type:
        $ref: '#/definitions/domain.AccountType'
      updated_at:
        type: string
    type: object
  dto.CreateAccountRequest:
    properties:
      color:
        type: string
      currency:
        type: string
      icon:
        type: string
      initial_balance:
        type: number
      name:
        type: string
      tenant_id:
        type: string
      type:
        $ref: '#/definitions/domain.AccountType'
    required:
    - name
    - tenant_id
    - type
    type: object
  handler.ErrorResponse:
    properties:
      error:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Financial tracking API documentation.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: FinTrack API
  version: "1.0"
paths:
  /accounts:
    get:
      consumes:
      - application/json
      description: list accounts by tenant ID
      parameters:
      - description: Tenant ID
        in: query
        name: tenant_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.AccountResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: List accounts
      tags:
      - accounts
    post:
      consumes:
      - application/json
      description: create a new account
      parameters:
      - description: Create account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/dto.CreateAccountRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.AccountResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Create an account
      tags:
      - accounts
  /accounts/{id}:
    get:
      consumes:
      - application/json
      description: get account by ID
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      - description: Tenant ID
        in: header
        name: X-Tenant-ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.AccountResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - OAuth2Application: []
      summary: Get an account
      tags:
      - accounts
securityDefinitions:
  OAuth2Application:
    flow: application
    type: oauth2
swagger: "2.0"
